# Generated by repro: do not edit by hand
# Please edit Dockerfiles in .repro/
FROM rocker/verse:4.2.1
ARG BUILD_DATE=2022-09-10
WORKDIR /home/rstudio
RUN apt-get update -y && apt-get install -y rsync
RUN install2.r --error --skipinstalled \ 
  here \ 
  lubridate \ 
  tidyverse
RUN installGithub.r \ 
  aaronpeikert/repro@fc7e884
